language: rust

cache:
  directories:
    - /home/travis/.cargo

matrix:
  include:
    - rust: nightly
      script: cargo test
    - rust: beta
      script: cargo check --manifest-path examples/stdweb/Cargo.toml
    - rust: stable
      script: cargo check --manifest-path examples/stdweb/Cargo.toml
