[package]
name = "typed-html-macros"
version = "0.1.0"
authors = ["Bodil Stokke <bodil@bodil.org>"]
build = "build.rs"

[lib]
proc-macro = true

[dependencies]
lalrpop-util = "0.16.1"
ansi_term = "0.11.0"

[build-dependencies]
lalrpop = "0.16.1"
