[package]
name = "typed-html-macros"
version = "0.1.0"
authors = ["Bodil Stokke <bodil@bodil.org>"]
build = "build.rs"

[lib]
proc-macro = true

[dependencies]
pom = "2.0.1"
lalrpop-util = "0.16.1"

[build-dependencies]
lalrpop = "0.16.1"
