[package]
name = "typed-html"
version = "0.1.0"
authors = ["Bodil Stokke <bodil@bodil.org>"]

[dependencies]
typed-html-macros = { path = "../macros" }
strum = "0.11.0"
strum_macros = "0.11.0"
mime = "0.3.12"
language-tags = "0.2.2"
enumset = "0.3.12"
http = "0.1.13"
